# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b019f5c3-5876-4dcc-afad-cd668be6a514";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F6B8-FAA7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

###############
#   Graphic   #
###############

  # 2. Graphics Enable: เปิดใช้งาน Mesa และ OpenGL
  hardware.graphics = {
    enable = true;
    
    # สำคัญ! เปิดรองรับ 32-bit (สำหรับ Steam, Wine, Lutris)
    enable32Bit = true; 

    # 3. Hardware Acceleration (VAAPI): ให้ GPU ช่วยถอดรหัสวิดีโอ
    extraPackages = with pkgs; [
      intel-media-driver   # Driver หลักสำหรับ Intel รุ่นใหม่ (Broadwell+) *แนะนำตัวนี้*
      intel-vaapi-driver   # Driver ตัวเก่า (เผื่อไว้เป็น Fallback แต่ปกติไม่ค่อยใช้แล้ว)
      libvdpau-va-gl       # แปลง VDPAU (ของ Nvidia เดิม) ให้วิ่งผ่าน VAAPI
    ];
  };

  # 4. System Environment Variables (บังคับบางแอปให้รู้จัก Driver)
  environment.sessionVariables = { 
    # บอกให้ Firefox/Chrome รู้ว่าให้ใช้ Driver ตัวไหนถอดรหัสวิดีโอ
    LIBVA_DRIVER_NAME = "iHD"; 
  };

  # 5. Tools: ติดตั้งเครื่องมือไว้เช็คสถานะ GPU
  environment.systemPackages = with pkgs; [
    mesa# มี glxinfo ไว้เช็ค OpenGL
    vulkan-tools    # มี vulkaninfo ไว้เช็ค Vulkan
    intel-gpu-tools # มี intel_gpu_top ไว้ดู Load ของ GPU (เหมือน htop แต่เป็น GPU)
    libva-utils     # มี vainfo ไว้เช็ค Video Codec
  ];
}
